# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flare < Formula
  desc ""
  homepage "https://github.com/kubefirst/flare"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubefirst/flare/releases/download/0.0.5/flare_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "4764e4d3456ecca8f71ce88df05be9efcad5de893cbaf043e792829c69cbf679"

      def install
        bin.install "flare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubefirst/flare/releases/download/0.0.5/flare_0.0.5_Darwin_arm64.tar.gz"
      sha256 "a2d3cfef5301da3ce18bd9e8a473e83ea23d3d22c353f3a43a66784c327d7f66"

      def install
        bin.install "flare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubefirst/flare/releases/download/0.0.5/flare_0.0.5_Linux_x86_64.tar.gz"
      sha256 "22090ad7672fa8e7163aab874d208295623fa3d167aa0b4254ee8ed58b4f02a2"

      def install
        bin.install "flare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubefirst/flare/releases/download/0.0.5/flare_0.0.5_Linux_arm64.tar.gz"
      sha256 "d9820b3f0fbc5cb24f3e5609a42ec2ec379e4b6249f37ffd5c770d478aa1e664"

      def install
        bin.install "flare"
      end
    end
  end
end
