# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefirst < Formula
  desc ""
  homepage "https://github.com/kubefirst/kubefirst"
  version "1.8.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubefirst/kubefirst/releases/download/1.8.4/kubefirst_1.8.4_Darwin_arm64.tar.gz"
      sha256 "13c73f619cd6def2e03d1e7ffbc0c3d5c97cb8ac421330aff5e20a158ea1696a"

      def install
        bin.install "kubefirst"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubefirst/kubefirst/releases/download/1.8.4/kubefirst_1.8.4_Darwin_x86_64.tar.gz"
      sha256 "c4fabf3f8bc4ff54ef6330aacccbfcfdabb6037a8fd8293ca965cbce6e81e55d"

      def install
        bin.install "kubefirst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubefirst/kubefirst/releases/download/1.8.4/kubefirst_1.8.4_Linux_arm64.tar.gz"
      sha256 "9401025431b88dea190c0467421ef71efe323710914ca75ef79f51ef14033d6a"

      def install
        bin.install "kubefirst"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubefirst/kubefirst/releases/download/1.8.4/kubefirst_1.8.4_Linux_x86_64.tar.gz"
      sha256 "607696c3d25c6afd3928c183060ba538683f68cb41f4a4e724b517da8caa400f"

      def install
        bin.install "kubefirst"
      end
    end
  end
end
