# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefirst < Formula
  desc ""
  homepage "https://github.com/kubefirst/kubefirst"
  version "2.4.5"

  depends_on "aws-iam-authenticator"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubefirst/kubefirst/releases/download/v2.4.5/kubefirst_2.4.5_darwin_amd64.tar.gz"
      sha256 "d44ec63a19ffce5545c3e11d3eaf9085096980d6334a97de803d39b46bb27e88"

      def install
        bin.install "kubefirst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubefirst/kubefirst/releases/download/v2.4.5/kubefirst_2.4.5_darwin_arm64.tar.gz"
      sha256 "042d811ff0a286f42c48eb77858e05d9a849d8e48263244bdf7ab2eb0aeeee99"

      def install
        bin.install "kubefirst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubefirst/kubefirst/releases/download/v2.4.5/kubefirst_2.4.5_linux_amd64.tar.gz"
      sha256 "ff52b77e70cdc67456c11768bff60d91e8af801f6fdb5ea7544bdd1841b38b63"

      def install
        bin.install "kubefirst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubefirst/kubefirst/releases/download/v2.4.5/kubefirst_2.4.5_linux_arm64.tar.gz"
      sha256 "313d92cbbd7796456f199a98a5bb6f402c374ae48e98b63f9c6a9a6028bff886"

      def install
        bin.install "kubefirst"
      end
    end
  end
end
