# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefirst < Formula
  desc ""
  homepage "https://github.com/kubefirst/kubefirst"
  version "1.10.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubefirst/kubefirst/releases/download/1.10.9/kubefirst_1.10.9_darwin_amd64.tar.gz"
      sha256 "34deeac1a04fd8e309335c6bbdfd489fc89254143b093e14fd24864b5950ecd9"

      def install
        bin.install "kubefirst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubefirst/kubefirst/releases/download/1.10.9/kubefirst_1.10.9_darwin_arm64.tar.gz"
      sha256 "c984c1854edf9428549e6ba85e1f5ad3a4476da3e7b6ff96d066dc4f80b39b3f"

      def install
        bin.install "kubefirst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubefirst/kubefirst/releases/download/1.10.9/kubefirst_1.10.9_linux_arm64.tar.gz"
      sha256 "6481784bfcc88504312afb8c2becee3ed5cf88aedba4ddf4a616bd32126cf121"

      def install
        bin.install "kubefirst"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubefirst/kubefirst/releases/download/1.10.9/kubefirst_1.10.9_linux_amd64.tar.gz"
      sha256 "b4991fa4d1b8aa8906d94d404246f690114376d83026078c0184f6f9389bcee6"

      def install
        bin.install "kubefirst"
      end
    end
  end
end
